### ISSUE TITLE
Paella builds fail when no git repository

### ISSUE THREAD

**Issue by miesgre** [polimediaupv/paella#262]
## Steps to reproduce:
1. Download paella from github release page
2. Try to build paella
 
## Actual Behavior:
 Build error:
```
[11:34:22] Using gulpfile /tmp/paella-master/gulpfile.js
[11:34:22] Starting 'compile'...
fatal: Not a git repository (or any of the parent directories): .git
[11:34:22] 'compile' errored after 25 ms
[11:34:22] Error: Command failed: git show --oneline -s
fatal: Not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at getVersion (/tmp/paella-master/gulpfile.js:22:12)
    at Gulp.<anonymous> (/tmp/paella-master/gulpfile.js:45:29)
    at module.exports (/tmp/paella-master/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/tmp/paella-master/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/tmp/paella-master/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/tmp/paella-master/node_modules/orchestrator/index.js:134:8)
    at /tmp/node-v6.10.3-linux-x64/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
```
 
## Expected Behavior:
Paella should be compiled

**Comment by ferserc1** [comment]
Fixed in Paella 5.2
