### ISSUE TITLE
Build.release broken on branch develop

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#320]
## Steps to reproduce:
1. git clone https://github.com/polimediaupv/paella.git paella-test
Cloning into 'paella-test'...
remote: Counting objects: 11513, done.
remote: Total 11513 (delta 0), reused 0 (delta 0), pack-reused 11513
Receiving objects: 100% (11513/11513), 153.25 MiB | 2.21 MiB/s, done.
Resolving deltas: 100% (7441/7441), done.

2. cd paella-test/

3.git checkout develop
Branch develop set up to track remote branch develop from origin.
Switched to a new branch 'develop'

4. npm install
added 586 packages in 13.134s

5. gulp build.release
[15:44:40] Using gulpfile ~/Development/paella-test/gulpfile.js
[15:44:40] Starting 'compileES5'...
[15:44:41] Starting 'compileES2015'...
[15:44:41] Starting 'styles'...
[15:44:41] Starting 'dictionary'...
[15:44:41] Starting 'copy'...
[15:44:41] Finished 'styles' after 106 ms
[15:44:41] Finished 'dictionary' after 89 ms
[15:44:41] Finished 'copy' after 85 ms

events.js:182
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Users/stauber/Development/paella-test/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at wrapper (/Users/stauber/Development/paella-test/node_modules/gulp-uglify/node_modules/lodash/_createHybrid.js:87:15)
    at trycatch (/Users/stauber/Development/paella-test/node_modules/gulp-uglify/minifier.js:26:12)
    at DestroyableTransform.minify [as _transform] (/Users/stauber/Development/paella-test/node_modules/gulp-uglify/minifier.js:79:19)
    at DestroyableTransform.Transform._read (/Users/stauber/Development/paella-test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/stauber/Development/paella-test/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/stauber/Development/paella-test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/stauber/Development/paella-test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/Users/stauber/Development/paella-test/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Transform.ondata (/Users/stauber/Development/paella-test/node_modules/gulp-replace/node_modules/readable-stream/lib/_stream_readable.js:612:20)
macsps:paella-test stauber$ 

Remarks:

- I've  tested with newer versions of gulp-minify and gulp-uglify, too. Same result.
- build.debug works (on branch develop) 
- build.release works (on branch master)

**Comment by karendolan** [comment]
Sven,

I added noted this issue in my pull as well. I think it’s a bug with the newer gulp uglify. 
https://github.com/polimediaupv/paella/pull/313

- Karen

**Comment by staubesv** [comment]
Thanks! I've included https://github.com/polimediaupv/paella/pull/313/commits/da3c54cbf1b544d1fd6da7a3bf29b419c803db81
 which made build.release work!

It seems that hls.min.js contains the line causing problems...

**Comment by staubesv** [comment]
@karendolan I've found the problem (see #321). Note that you can remove the debug()'s around uglify() - while it makes build.release work, the resulting file sizes indicate that no uglification was performed at all.

**Comment by karendolan** [comment]
@staubesv thanks!

**Comment by staubesv** [comment]
This issue has been fixed by #321.
